name: Fetch Progress Image

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:         # allow manual run

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Fetch latest image
        run: python .github/scripts/fetch_image.py

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add photos/today.jpg
          git commit -m "Update daily photo" || echo "No changes"
          git push
